version: "3.7"

services:
  database:
    image: mysql:5.7
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: P123456p
      MYSQL_DATABASE: bookstore_db
      MYSQL_USER: clarusway
      MYSQL_PASSWORD: Clarusway_1
    ports:
      - "3306:3306"
    volumes:
      -  mydata:/var/lib/mysql
    # labels:
    #   kompose.volume.type: "persistentVolumeClaim" 
    #   kompose.volume.size: "5Gi"
    #   kompose.volume.storage-class-name: "my-sc"
    networks:
      - clarusnet

  myapp:
    image: olivercw/bookstoreapi:latest 
    container_name: myapp
    restart: always 
    depends_on:
      - database
    ports:
      - "80:80"
    # labels:
    #   kompose.service.expose: "oliver.clarusway.us"
    #   kompose.service.type: "nodeport"
    #   kompose.service.nodeport.port: "30001"
    #   kompose.service.expose.ingress-class-name: "nginx"
    networks:
      - clarusnet

networks:
  clarusnet:
    driver: bridge

volumes: 
  mydata:
 